using error catching

test "permission":

    set {_context} to a new luckperms context with key "gamemode" and value "creative"

    set {_permission} to a new luckperms permission with key "test-permission":
        set expiry of event-permission to 94 hours
        set context of event-permission to {_context}

    assert value of {_permission} is "test-permission" with "Failed to create a permission node with key 'test-permission'"
    assert expiry of {_permission} is 94 hours with "Failed to set expiry of a permission"
    set {_context} to context of {_permission}
    set {_context::key} to (context key of {_context})
    set {_context::value} to value of {_context}
    assert {_context::key} is "gamemode" with "Failed to set context of a permission with key 'gamemode'"
    assert {_context::value} is "creative" with "Failed to set context of a permission with value 'creative'"

    # Ensure that even after being added to a user and retrieved, the permission info is the same

    set {_user} to test-luckperms user
    edit luckperms user {_user}:
        add {_permission} to luckperms permissions of event-user

    set {_user} to luckperms user from test-offline player

    loop luckperms permissions of {_user}:
        if value of loop-value is "test-permission":
            set {_user::permission} to loop-value
            stop loop

    assert unsafely {_user::permission} is set with "Failed to add a permission to a user"

    assert unsafely value of {_user::permission} is "test-permission" with "Failed to get value of a permission from a user"
    assert unsafely expiry of {_user::permission} is 94 hours with "Failed to get expiry of a permission from a user"
    set {_context} to context of {_user::permission}
    set {_context::key} to context key of {_context}
    set {_context::value} to value of {_context}
    assert unsafely {_context::key} is "gamemode" with "Failed to get context of a permission from a user with key 'gamemode'"
    assert unsafely {_context::value} is "creative" with "Failed to get context of a permission from a user with value 'creative'"

    set {_error} to "You can only change the context of a permission node inside a 'permission' section."
    catch runtime errors:
        set context of {_permission} to {_context}

    assert unsafely last caught errors is {_error} with "Set context outside of a permission section should error but did not"

    set {_error} to "You can only change the expiry of a permission node inside a 'permission' section."
    catch runtime errors:
        set expiry of {_permission} to 18 hours

    assert unsafely last caught errors is {_error} with "Set expiry outside of a permission section should error but did not"

    edit luckperms user {_user}:
        reset luckperms permissions of event-user